import 'package:flutter/cupertino.dart';

const Color grayColor = Color(0xFFA0A0A0);
const Color blackColor = Color(0xFF414141);
const Color backgroundColor = Color(0xFFF5FAF8);
const Color greencolor = Color(0xFF237642);
const Color grayColor2 = Color(0xFF636363);
const Color grayColor3 = Color(0xFFD4D4D4);
const Color borderColor = Color(0xFFDBE4E1);
const Color whiteColor = Color(0xFFFEFEFE);
const Color activeborderColor = Color(0xFF969D9A);
const Color dialogTextColor = Color(0xFF6C8A7E);
const Color dialogBackgroundColor = Color(0xFFE6F2ED);
const Color hintColor = Color(0xFF858585);
const Color containerColor = Color(0xFFEAF4F0);
const Color cameraovalColor = Color(0xFFAEB0AF);
const Color ovalfillColor = Color(0xFFECECEC);
const Color avatarborderColor = Color(0xFF0AAF48);
const Color uploadButtonborderColor = Color(0xFF828E89);
const Color tickbackgroundColor = Color(0xFFB8EFCC);
const Color cardtopcolor = Color(0xFFD9E7E1);
